#! /bin/sh


#-------------- Kill already running --------------------

killall -9 ksuperkey lxpolkit.ui lxpolkit greenclip daemon &
pkill -USR1 polybar &
pkill -USR1 redshift &

#----------------start running ------------------------

#rm .Xauthority &
dunst &
pcmanfm -d &
xrandr --output LVDS1 --off &
xrandr --output VGA1 --primary &
sxhkd &
./Scripts/resolucionsh.sh &
picom &
/usr/lib/gpaste/gpaste-daemon &
# launch polybar
nitrogen --restore & 
~/.config/polybar/launch.sh &
nm-applet &
#/usr/lib/geoclue-2.0/demos/agent &

#lxpolkit
/usr/lib/lxpolkit/lxpolkit ui/lxpolkit.ui &

#gnome-polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# fix greenclip manager
greenclip daemon>/dev/null &


#tilix calcurse -e calcurse &

#-------------- your favority wallpaper -------------------

#feh --bg-fill /home/j/Pictures/44.jpg &

#bspc config pointer_modifier mod1 &

#-------------------- Fix cursor-------------------------

xsetroot -cursor_name left_ptr &

# 
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}


#---------------- workspaces ----------------------------------- 
bspc monitor VGA1 -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
#		bspc monitor VGA1 -n "$name" -d '' '' '' '' '' '' '' ''


#--------bspwm config {border, colors, focused}-------------------

bspc config border_width 3
bspc config window_gap          0
#bspc config normal_border_color "#75B9C8"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#75B9C8"
bspc config focused_border_color "#81A1C1"
#"#9E9E9E"
bspc config presel_feedback_color "#6272a4"


SPACES=$(bspc query -D)
for SPACE in $SPACES
do
  bspc config -d ${SPACE} window_gap      0
  bspc config -d ${SPACE} top_padding     0
  bspc config -d ${SPACE} bottom_padding 0
  bspc config -d ${SPACE} left_padding  0
  bspc config -d ${SPACE} right_padding  0
done

#monitor_focus <I>
bspc config automatic_scheme      spiral
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true

#-------desktop bspwm--------------------------------

bspc desktop ^1 -l monocle
bspc desktop ^2 -l alternate
bspc desktop ^3 -l alternate
bspc desktop ^4 -l monocle
bspc desktop ^5 -l monocle
bspc desktop ^6 -l alternate
bspc desktop ^7 -l alternate
bspc desktop ^8 -l alternate
bspc desktop ^9 -l monocle
bspc desktop ^10 -l monocle


#-------- Rules----------------------------------------

#rule -a tilix:Tiled desktop='^1' follow=on
#bspc rule -a tilix:Tmux desktop='^1' follow=on
bspc rule -a chromiun desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a librewolf desktop='^1'
bspc rule -a Brave desktop='^1'
bspc rule -a tilix desktop='^1'
bspc rule -a polybar desktop='^1'
#bspc rule -a Subl3 desktop='^3'
#bspc rule -a Thunar desktop='^4' state=pseudo_tiled
#bspc rule -a Thunar desktop='^4'
bspc rule -a Thunar:Dialog state=floating center=true
bspc rule -a whatsdesk desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^5' follow=on
#bspc rule -a discord desktop='^6' follow=on
#bspc rule -a Gimp-2.10 desktop='^6'
#bspc rule -a Inkscape desktop='^6'
#bspc rule -a kdenlive desktop='^6'
#bspc rule -a Audacious desktop='^7' state=floating follow=on focus=on
bspc rule -a xstate=tiled follow=on
#bspc rule -a '*:libreoffice' desktop='^5' state=tiled
bspc rule -a Zathura state=tiled follow=on
#bspc rule -a '*:soffice' desktop='^8'
#bspc rule -a Gnome-chess desktop='^9'
#bspc rule -a teeworlds desktop='^9'
#bspc rule -a Steam desktop='^9' state=floating
#bspc rule -a "VirtualBox Manager" desktop='^10'

bspc rule -a tilix:Newsboat state=floating center=on
bspc rule -a tilix:Ranger state=floating center=on
bspc rule -a tilix:Pacui state=floating center=on
bspc rule -a tilix:Float state=floating
bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating
bspc rule -a GParted state=floating
bspc rule -a File-roller state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Lxrandr state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a qt5ct state=floating rectangle=700x470+0+0 center=on
bspc rule -a SimpleScreenRecorder desktop="^7" state=floating rectangle=500x570+0+0 center=on
bspc rule -a Sxiv state=floating sticky=on rectangle=328x220+1015+510
bspc rule -a Viewnior state=floating
bspc rule -a SMPlayer state=floating
bspc rule -a mpv state=floating sticky=on rectangle=320x198+1020+490
bspc rule -a pavucontrol state=floating center=true  
bspc rule -a vlc state=floating center=on rectangle=700x470+0+0
bspc rule -a python3 state=floating center=on rectangle=300x98+0+0
bspc rule -a galculator state=floating center=on 
bspc rule -a pamac-manager state=floating center=on rectangle=700x470+0+0
bspc rule -a tilix mpsyt -e mpsyt desktop="^6" 
bspc rule -a '*:Kunst' sticky=on layer=below border=off focus=off
bscp rule -a polybar manage=off
bspc rule -a Tint2 border=off manage=off layer=above state=floating
bscp rule -a Leafpad state=floating sticky=on center=on rectangle=700x470+0+0

#bscp rule -a netsurf state=floating center=on rectangle=700x470+0+0
#bspc rule -a Sxiv state=floating center=on rectangle=700x470+0+0
#rectangle=700x470+0+0
# bspc rule -a Mylaunchpad border=off manage=off
# bspc rule -a Sxiv:Kunst sticky=on layer=below border=off focus=off manage=off rectangle=250x250+1055+60



# Set Desktop 7 to start with floating windows
#FLOATING_DESKTOP_ID=$(bspc query -D -d '^7')
bspc subscribe node_manage | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[3]}
	[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done


